name: Continuous Integration
on:
  push:
    branches: [main]
    paths-ignore: [src/**, package.json, tsconfig*, yarn.lock, .github/workflows/*, .prettier*, .eslint*]
    tags-ignore: ['*']
  pull_request:
    branches: ['*']
    paths-ignore: [src/**, package.json, tsconfig*, yarn.lock, .github/workflows/*, .prettier*, .eslint*]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.5, 15, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v15
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build --noEmit

      - name: Test
        run: yarn lint
